### ISSUE TITLE
Furniture resetting on quota fail or eject

### ISSUE THREAD

**Issue by KleskReaver** [mattymatty97/LTC_FurnitureLock#1]
Hi there,

great mod! and great idea!
It seems to only be working on a fresh game save,
config is being ignored after eject sequence when failing to meet quota or using the eject command on terminal

Edit: also the default values of 0, 0, 0 for the Teleporter and Inverse Teleporter are spawning them on a strange diagonal angle, I noticed the first rotation value on other objects was 270 after you move them once, so I tried 270 on the Teleporters and that seems to fix them

cheers

**Comment by mattymatty97** [comment]
yeah there are still few things to iron out.

can you tell me the version that caused the rotated teleporter?

i will try to fix the issue for eject soon

**Comment by KleskReaver** [comment]
> yeah there are still few things to iron out.
> 
> can you tell me the version that caused the rotated teleporter?
> 
> i will try to fix the issue for eject soon

I'm sure it was 1.2.2 but I'll have to check when I'm home tonight (Australia time)

**Comment by KleskReaver** [comment]
hey bud, i've been testing version 1.2.5

still not reading from config, i tried both the terminal eject and not meeting quota

I've currently got a work around, if you have all furniture locked, you just need to attempt to move them and they will snap to the config values, great mod! keep it up!

**Comment by mattymatty97** [comment]
thanks for the encouragement, apparently there were even more typos preventing the patch from working as intended

hopefully all will work in v1.2.6

**Comment by KleskReaver** [comment]
> thanks for the encouragement, apparently there were even more typos preventing the patch from working as intended
> 
> hopefully all will work in v1.2.6

testing 1.2.6, working great! furniture is going to config value locations on eject and quota fail

BUT! xD, the config option for "spawn_stored" is likely being ignored on eject and quota fail, it is working on a fresh save though.

I test this with Bunkbeds "spawn_stored" set to true,
On a fresh game save, it is stored in the terminal.
But on eject or quota fail the Bunkbeds are in the ship.

thanks for all your work on this, mod is super good as-is, just wanted to let you know my findings with it
