### ISSUE TITLE
Some furniture going back to normal spot on eject

### ISSUE THREAD

**Issue by AkumaNoTenshi** [mattymatty97/LTC_FurnitureLock#3]
I think It's because of the Build_Anywhere mod. I think it try's to move it but fails because its not in the ship placing zone

01913a4e-61e2-9a52-3bbd-f0759e54d38e

Here is the code if you need it

Note: Sometimes you have to import it twice for all of the configs to all load And it's 1.45 GB Sorry if it's too big

**Comment by mattymatty97** [comment]
i'll be unable to test it for a while,
but crom what i can see the Build_Anywhere mod is working outside of the vanilla system, maybe try [BetterDecorPlacement](https://thunderstore.io/c/lethal-company/p/ViViKo/BetterDecorPlacement/)

**Comment by AkumaNoTenshi** [comment]
Tried it and it did not, Still has the same problem.

**Comment by mattymatty97** [comment]
please define "normal spot"
