### ISSUE TITLE
v60 update with Cupboard

### ISSUE THREAD

**Issue by KleskReaver** [mattymatty97/LTC_FurnitureLock#4]
hey bud

v60 game update has changed something about the Cupboard and is spawning it in the default location ignoring FurnitureLock setting

you can use the easy work-around of trying to move it and it will snap to the config location

This issue seems to only happen once per game launch and on a fresh save file.

exiting to the main menu, deleting your game save file and creating a new one will spawn the cupboard in the config location but exiting Lethal Company completely and re-launching it seems to be where it has this issue

only a small issue so this is mainly an FYI, not a "ZOMG v60 BROKEH MAH MODS" report :D

**Comment by KleskReaver** [comment]
This seems to be fixed with v61 hotfix of the game, but ill test other furniture as I get access to them

**Comment by mattymatty97** [comment]
yeah it was an issue from zeekers and he silently fixed it in v61
